definitions:
  user.UserInfo:
    properties:
      id:
        example: 1
        format: int64
        type: integer
      name:
        example: account name
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/healthCheck:
    get:
      consumes:
      - application/json
      description: check server status
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: health check for server
  /user/{name}:
    get:
      consumes:
      - application/json
      description: 입력된 유저의 정보를 반환해주는 API
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserInfo'
      summary: 유저 정보 가져오기
swagger: "2.0"
