definitions:
  controller.UserInfo:
    properties:
      id:
        example: 1
        format: int64
        type: integer
      name:
        example: account name
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/healthCheck:
    get:
      consumes:
      - application/json
      description: check server status
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: health check for server
  /user/{name}:
    get:
      consumes:
      - application/json
      description: get user name, id
      parameters:
      - description: User name
        in: path
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserInfo'
      summary: get user name
swagger: "2.0"
